### ISSUE TITLE
Stream does not expose method to get mutated struct

### ISSUE THREAD

**Issue by yilinwei** [djg/cubeb-rs#15]
Hi,

For both of the input and output streams, it's unclear how to get the mutated struct that the callback uses since ownership is handed over.

~~Would it be sensible if the `stop` function returned a `Result<T>` rather than `Result<()>`?~~

**Comment by djg** [comment]
Thanks for raising this issue. The callback struct is a bit of an experiment in trying to make the cubeb C callbacks more rust-like.  To help me understand, can you explain how you're using the callback struct?

**Comment by yilinwei** [comment]
I see.

I was attempting to port the record example from the c repository. It essentially defines a c struct, mutates it within the callback and then asserts whether the struct has had a field changed after the callback has stopped executing.

This isn't particularly nice in rust because once you've handed over the struct, rust basically says (correctly imo) that you've handed over ownership and I should probably be using channels to communicate between the threads. However with the callback tied to struct it's not particularly easy to do - ideally this should be similar to the [threading API](https://doc.rust-lang.org/book/second-edition/ch16-02-message-passing.html) with closures.

This is just doing it implicitly rather than explicitly like is currently being done. There's some info [here](https://stackoverflow.com/questions/32270030/how-do-i-convert-a-rust-closure-to-a-c-style-callback).

Ideally on the `cubeb::Context` I'd like to have methods like,

```
    fn input_stream<T, F>(&self, params: StreamParameters<T>, f: F) -> Stream
    where
        F: FnMut(&[T]) -> Cont,
        F: Send + 'static,
    {

        unimplemented!()
    }

    fn output_stream<T, F>(&self, params: StreamParameters<T>, f: F) -> Stream
    where
        F: FnMut(&mut [T]) -> Cont,
        F: Send + 'static,
    {
        unimplemented!()
    }

    fn duplex_stream<T1, T2, F>(&self, input_params: StreamParameters<T1>, output_params: StreamParameters<T2>, f: F) -> Stream
    where
        F: FnMut(&[T1], &mut [T2]) -> Cont,
    {
        unimplemented!()
    }

```

and `output_stream`, 'duplex_stream` and maybe `scan` variants with two callbacks (for state and normal like you've done since the struct essentially has to be shared between both).

So then the syntax looks something more like,

```
    let mut a = Foo(1);
    let stream = ctx.input_stream(
        StreamParameters {
            layout: 1,
            rate: 4,
            channels: 1,
            format: SampleFormat::Float32BE
        },
        move |x| {
            a.0 = 4;
            Cont::Next(x.len())
        }
    );
```

The `Stream` handle returned would essentially give you back something to do your queries and `stop()/start()`. 

I'm aware that this is quite a departure from your current API though, so I'm happy to a) do the work and submit a PR or b) leave the alternative API in a different place.

**Comment by djg** [comment]
Hi @yilinwei, The interface to stream callbacks has been totally reworked in `v0.4`.  If you are still using this crate could you give it a try and report back?

thanks,
Dan

**Comment by yilinwei** [comment]
@djg Will do; I'll try and set aside some time this weekend and report back.
