### ISSUE TITLE
Anything I could help with?

### ISSUE THREAD

**Issue by Limeth** [djg/cubeb-rs#2]
Due to the lack of a feature-complete cubeb library on crates.io, I started working on [my Rust wrapper for the Cubeb library](https://github.com/Limeth/cubeb-rs). Later it was pointed out to me that this repository exists. I doubt there would be any point in maintaining two separate wrappers for the library, so I guess I'll discontinue mine.
Anything I could help out with here?

**Comment by djg** [comment]
Hi @Limeth,

Thanks for the enquiry. This crate will be integrated in Mozilla Gecko fairly soon as part of cubeb usage refactoring we are currently working on.  Part (djg/cubeb-pulse-rs) is already landed in Gecko. To collect all the various local crates I had, I started this project to provide a common collection of type wrappers for both the public Cubeb API and the internals of Cubeb for implementing backends (such as djg/cubeb-pulse-rs).

I've been working on a reorganization that is mostly complete. (https://github.com/djg/cubeb-rs/tree/workspace-reorg/). What is really needed is for testing of the API by using the code for more than just small examples.

**Comment by Limeth** [comment]
Thanks for the response,
I will be making a use of the API in a [project of mine](https://github.com/Limeth/streamsplash) I'm making in order to learn a bit of audio processing and Vulkan shaders.
Feel free to close this issue.

**Comment by djg** [comment]
I'm interested in how you find working with streams is. It's a bit experimental at this stage.
