### ISSUE TITLE
Access to publish releases on crates.io

### ISSUE THREAD

**Issue by kinetiknz** [djg/cubeb-rs#35]
Can you please add me as an owner of the cubeb crates on crates.io so I can published the latest (minor) changes to be picked up in Gecko?  Instructions [here](https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-owner).  Thanks!

**Comment by djg** [comment]
I've requested your username be added as an owner.

**Comment by kinetiknz** [comment]
Thanks! Accepted invites.
