### ISSUE TITLE
Nightly build broken for quite a while

### ISSUE THREAD

**Issue by kinetiknz** [djg/cubeb-rs#38]
The Nightly CircleCI build starting failing a while back with:
```
Compiling serde_json v1.0.34
error[E0599]: no function or associated item named `to_u128` found for type `num_traits::ToPrimitive` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/extprim-1.6.0/src/traits.rs:250:9
```

The Rust compilers in use are fairly old now (nightly is 1.25).  serde_json requires 1.26 for [ui]128 support.  cubeb-rs builds locally with current nightly, so probably the simplest fix is to update the CircleCI build image with newer Rust compilers.

@djg Where does the mozmedia/cubeb-rust:fc27 image live and how do we go about updating it?

**Comment by djg** [comment]
The `mozmedia/cubeb-rust` image lives on `docker hub`. I've added the `Dockerfile` that was used to create the images in PR #39. I added detail of the instructions to run to create and publish a new image with `docker`.
