### ISSUE TITLE
Getting an error code `3` when calling `stream_init`

### ISSUE THREAD

**Issue by Limeth** [djg/cubeb-rs#4]
Compiling & running [my project](https://github.com/Limeth/streamsplash/tree/b9c383a79423678d263a614e697000325886091e) results in `Context::init_stream` returning an error with an unrecognized code `3`, I have no idea what I did wrong that resulted in this behavior.
The "audio part" of `main.rs` ends at line 130, the rest of the code isn't being invoked.
I run the project with `env RUST_BACKTRACE=full cargo run --release` to list the available devices and then with `env RUST_BACKTRACE=full cargo run --release -- 0` where `0` is the selected device index. This second command produces the error.

```
     Running `target/release/streamsplash 2`
Selected device: Monitor of Cyborg F.R.E.Q.5 Gaming Headset  Digital Stereo (IEC958)
thread 'main' panicked at 'Failed to create Cubeb stream: Error { code: 3 }', src/main.rs:122
stack backtrace:
   0:     0x5610c01f2c03 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::hcab99e0793da62c7
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x5610c01efb36 - std::sys_common::backtrace::_print::hbfe5b0c7e79c0711
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
   2:     0x5610c01f444a - std::panicking::default_hook::{{closure}}::h9ba2c6973907a2be
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:355
   3:     0x5610c01f404b - std::panicking::default_hook::he4d55e2dd21c3cca
                               at /checkout/src/libstd/panicking.rs:371
   4:     0x5610c01f479b - std::panicking::rust_panic_with_hook::ha138c05cd33ad44d
                               at /checkout/src/libstd/panicking.rs:549
   5:     0x5610c01f4674 - std::panicking::begin_panic::hcdbfa35c94142fa2
                               at /checkout/src/libstd/panicking.rs:511
   6:     0x5610c01f45a9 - std::panicking::begin_panic_fmt::hc09fe500d9b7be81
                               at /checkout/src/libstd/panicking.rs:495
   7:     0x5610c01d6b05 - streamsplash::main::hdbc97505bfaa57c0
   8:     0x5610c01fb1fa - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:98
   9:     0x5610c01f4dc8 - std::rt::lang_start::ha09816a4e25587ea
                               at /checkout/src/libstd/panicking.rs:433
                               at /checkout/src/libstd/panic.rs:361
                               at /checkout/src/libstd/rt.rs:59
  10:     0x7f001e59082f - __libc_start_main
  11:     0x5610c01d5c18 - _start
  12:                0x0 - <unknown>
```

Any help would be much appreciated.

**Comment by djg** [comment]
Hi,
I switched your project over from master branch to workspace-reorg branch. Error 3 was replaced with "Invalid Parameter".  It appears that cubeb is returning 0 for high/lo latency which is then rejected when trying to create a new stream.

I wonder if we can't come up with a better interface to catch this, like putting the validation check into take() of the StreamInitParamsBuilder?

**Comment by Limeth** [comment]
If a latency of 0 is always invalid, maybe it would be a good idea to make `DeviceInfo::latency_lo` and `DeviceInfo::latency_hi` return either `Option<u32>` or `Result<u32>` to indicate when it shouldn't be used when constructing a `StreamInitOptions`.
